/**
 * arc/sharedLiveSessionFacts.ts
 *
 * Adaptive ARC architecture task (unified PD/ARC Goal), Phase 2: the
 * track-neutral, track-DISCRIMINATED shared resolved-session type the
 * approved unified architecture calls for -- a thin union over each
 * track's own real facts shape, never a merged/flattened schema that
 * would force one track's concepts onto the other. `track` is the
 * discriminant; a consumer that only cares about one track narrows on it
 * exactly like any other discriminated union in this codebase.
 *
 * Personal Development's own side is a pure pass-through wrapper around
 * the REAL, existing, tested arc/combinedLiveSessionFacts.ts projection --
 * never a second, parallel copy of that shape.
 *
 * ArcGoal has no equivalent facts type today (confirmed: no
 * `terminalCompleted`-style field exists anywhere in arc/arcGoalEngine.ts's
 * ArcGoalLiveState or in the outer/inner ArcLiveState it drives -- "session
 * finished" is only ever detected screen-side, in
 * live/ArcGoalSessionScreen.tsx, via the outer run reaching ArcStage
 * "complete" and, separately and later, the trainee confirming the final
 * "goal_action_confirm" meta-stage). This module does not change that --
 * it adds a pure, read-only PROJECTION function
 * (toArcGoalSharedFacts) that takes the real outer ArcLiveState +
 * ArcGoalLiveState plus the few facts only the screen currently knows
 * (which mapping's own actionRelationship applies, and whether
 * goal_action_confirm was actually reached and confirmed) as explicit
 * inputs, mirroring exactly how toCombinedLiveSessionFacts is itself a
 * pure projection over CombinedLiveSessionState that invents nothing.
 *
 * Nothing in this repository calls anything below yet -- no BUILD/LIVE
 * wiring in this phase. Nothing here persists anything (no storage
 * import, no data/ import), and nothing here modifies
 * arc/arcGoalEngine.ts, arc/combinedLiveSession.ts, or either live
 * screen's own real behavior.
 */

import type { CombinedLiveSessionCadence, CombinedLiveSessionFacts } from "./combinedLiveSessionFacts.ts";
import { toCombinedLiveSessionFacts } from "./combinedLiveSessionFacts.ts";
import type { CombinedLiveSessionState } from "./combinedLiveSession.ts";
import type { ArcGoalLiveState } from "./arcGoalEngine.ts";
import type { ActionRelationship } from "./factorAction.ts";
import type { ArcLiveState, ExecutionMode } from "./types.ts";

export type LiveSessionTrack = "personal_development" | "arc_goal";

export interface PersonalDevelopmentSharedFacts {
  track: "personal_development";
  facts: CombinedLiveSessionFacts;
}

/**
 * Which of ArcGoal's own mapping kinds (arc/types.ts) this session's
 * bridge actually used. "thought"/"belief" exist here only for
 * forward-compatibility with Phase 1's new ArcGoalThoughtMapping/
 * ArcGoalBeliefMapping types -- arc/arcGoalEngine.ts has no selection
 * concept for either yet (only selectedMappingId/selectedUrgeMappingId,
 * see ArcGoalLiveState), so toArcGoalSharedFacts below can never actually
 * produce them today; a later phase that wires those mapping kinds into
 * the live engine is what would ever populate them.
 */
export type ArcGoalMappingKind = "interfering" | "urge" | "thought" | "belief";

export interface ArcGoalSharedFacts {
  track: "arc_goal";
  /** Caller-supplied -- ArcGoal has no session id concept in the engine itself today, the same way PersonalDevelopmentRouteProgress's own sessionId is generated by its LIVE screen, never by the engine. */
  sessionId: string;
  arcGoalId: string;
  /** The linked ScheduledRoutine's WeeklyAction, when this session was launched from one -- mirrors live/ArcGoalSessionScreen.tsx's own weeklyActionId param exactly. null otherwise. */
  weeklyActionId: string | null;
  /** null for an identity-only pass with no bridge selected at all (e.g. the goal has no interfering/urge mappings, or reassessmentChoice resolved to "direct"). */
  mappingKind: ArcGoalMappingKind | null;
  mappingId: string | null;
  executionMode: ExecutionMode | null;
  /** The selected mapping's own ActionRelationship (arc/types.ts's ArcGoalInterferingMapping/ArcGoalUrgeMapping.actionRelationship) -- this module has no access to ArcGoal's own mapping arrays, so the caller resolves and supplies it. null when mappingId is null. */
  actionRelationship: ActionRelationship | null;
  /** The outer (identity) run's own real-action confirmation -- mirrors ArcLiveState.realActionCompleted, the exact field live/ArcGoalSessionScreen.tsx's own finalizeOuterSession already reads for session-log "success". */
  identityActionCompleted: boolean;
  /** The outer identity run reached its own terminal ArcStage -- mirrors ArcLiveState.currentArcStage === "complete", the same condition live/ArcGoalSessionScreen.tsx's own commitAdvanceOuter already checks before calling finalizeOuterSession. Reaching this is NOT the same as the session being over -- gratitude/reflection and the final goal_action_confirm confirmation both still follow it (see terminalCompleted's own doc below). */
  outerRunCompleted: boolean;
  /**
   * The true end-to-end terminal signal for a full ArcGoal session --
   * mirrors ArcGoalUiStage "goal_action_confirm" having actually been
   * reached AND confirmed (live/ArcGoalSessionScreen.tsx's own
   * handleGoalActionConfirmDone, the only point at which a linked
   * routine is marked complete). Deliberately NOT derived from
   * outerRunCompleted alone -- the outer run reaching "complete" only
   * ends the identity-layer ArcStage sequence; gratitude/reflection and
   * the final real-goal-action confirmation both still follow it before
   * the session is genuinely over. Caller-supplied for the same reason
   * toArcGoalSharedFacts never reads screen-local React state directly.
   */
  terminalCompleted: boolean;
}

export type SharedLiveSessionFacts = PersonalDevelopmentSharedFacts | ArcGoalSharedFacts;

/**
 * Pure pass-through wrapper -- delegates entirely to the real, existing,
 * tested toCombinedLiveSessionFacts and tags the result with the shared
 * discriminant. Never a second, parallel derivation of the PD facts shape.
 */
export function toPersonalDevelopmentSharedFacts(state: CombinedLiveSessionState, cadence: CombinedLiveSessionCadence = "reactive"): PersonalDevelopmentSharedFacts {
  return { track: "personal_development", facts: toCombinedLiveSessionFacts(state, cadence) };
}

export interface ArcGoalSharedFactsInput {
  sessionId: string;
  arcGoalId: string;
  weeklyActionId: string | null;
  /** The outer (identity) run's own ArcLiveState, exactly as live/ArcGoalSessionScreen.tsx already holds it. */
  outerSession: ArcLiveState;
  /** The ArcGoal-only orchestration state, exactly as live/ArcGoalSessionScreen.tsx already holds it. */
  goalState: ArcGoalLiveState;
  /** The selected mapping's own ActionRelationship, resolved by the caller from ArcGoal.interferingMappings/urgeMappings -- see ArcGoalSharedFacts.actionRelationship's own doc for why this module can't resolve it itself. */
  mappingActionRelationship: ActionRelationship | null;
  /** See ArcGoalSharedFacts.terminalCompleted's own doc -- true only once the trainee has actually confirmed goal_action_confirm. */
  terminalCompleted: boolean;
}

/**
 * Pure projection -- callable at any point, but only meaningful once
 * `terminalCompleted` is genuinely true (this phase never persists it
 * either way, exactly like toCombinedLiveSessionFacts's own doc). Never
 * fabricates a mapping selection, execution mode, or completed action
 * that has not genuinely occurred -- every field is read directly off
 * `outerSession`/`goalState` or passed through verbatim from the caller.
 */
export function toArcGoalSharedFacts(input: ArcGoalSharedFactsInput): ArcGoalSharedFacts {
  const mappingKind: ArcGoalMappingKind | null =
    input.goalState.selectedMappingId !== null ? "interfering" : input.goalState.selectedUrgeMappingId !== null ? "urge" : null;
  const mappingId = input.goalState.selectedMappingId ?? input.goalState.selectedUrgeMappingId ?? null;

  return {
    track: "arc_goal",
    sessionId: input.sessionId,
    arcGoalId: input.arcGoalId,
    weeklyActionId: input.weeklyActionId,
    mappingKind,
    mappingId,
    executionMode: input.goalState.executionMode,
    actionRelationship: mappingId !== null ? input.mappingActionRelationship : null,
    identityActionCompleted: input.outerSession.realActionCompleted,
    outerRunCompleted: input.outerSession.currentArcStage === "complete",
    terminalCompleted: input.terminalCompleted,
  };
}
